-- CreateTable
CREATE TABLE `ADMIN` (
    `idADMIN` INTEGER NOT NULL,
    `nombre` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `ADMIN_email_key`(`email`),
    PRIMARY KEY (`idADMIN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REDES` (
    `idREDES` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idREDES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CENTRO` (
    `idCENTRO` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idCENTRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AMBIENTE` (
    `idAMBIENTE` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `caracteristicas` VARCHAR(500) NOT NULL,
    `centroId` INTEGER NOT NULL,

    PRIMARY KEY (`idAMBIENTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA` (
    `idPROGRAMA` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,
    `redesid` INTEGER NOT NULL,
    `centroId` INTEGER NOT NULL,

    PRIMARY KEY (`idPROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RECOMENDACION` (
    `idRECOMENDACION` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,
    `programaId` INTEGER NOT NULL,
    `reporteId` INTEGER NOT NULL,

    PRIMARY KEY (`idRECOMENDACION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ASPIRANTE` (
    `idASPIRANTE` INTEGER NOT NULL,
    `nombre_completo` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `telefono` VARCHAR(10) NOT NULL,
    `password` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`idASPIRANTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TEST` (
    `idTEST` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idTEST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REPORTE` (
    `idREPORTE` INTEGER NOT NULL AUTO_INCREMENT,
    `Fecha` DATETIME(3) NOT NULL,
    `testId` INTEGER NOT NULL,
    `aspiranteId` INTEGER NOT NULL,

    UNIQUE INDEX `REPORTE_testId_key`(`testId`),
    PRIMARY KEY (`idREPORTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREGUNTAS` (
    `idPREGUNTAS` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `testId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREGUNTAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESPUESTAS` (
    `idRESPUESTAS` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `preguntaId` INTEGER NOT NULL,

    PRIMARY KEY (`idRESPUESTAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESPUESTAS_ASPIRANTE` (
    `idRESPUESTASASP` INTEGER NOT NULL AUTO_INCREMENT,
    `aspiranteId` INTEGER NOT NULL,
    `testId` INTEGER NOT NULL,
    `preguntaId` INTEGER NOT NULL,
    `respuestaId` INTEGER NOT NULL,
    `reporteId` INTEGER NOT NULL,

    PRIMARY KEY (`idRESPUESTASASP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `AMBIENTE` ADD CONSTRAINT `AMBIENTE_centroId_fkey` FOREIGN KEY (`centroId`) REFERENCES `CENTRO`(`idCENTRO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_redesid_fkey` FOREIGN KEY (`redesid`) REFERENCES `REDES`(`idREDES`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_centroId_fkey` FOREIGN KEY (`centroId`) REFERENCES `CENTRO`(`idCENTRO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECOMENDACION` ADD CONSTRAINT `RECOMENDACION_programaId_fkey` FOREIGN KEY (`programaId`) REFERENCES `PROGRAMA`(`idPROGRAMA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RECOMENDACION` ADD CONSTRAINT `RECOMENDACION_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_aspiranteId_fkey` FOREIGN KEY (`aspiranteId`) REFERENCES `ASPIRANTE`(`idASPIRANTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREGUNTAS` ADD CONSTRAINT `PREGUNTAS_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS` ADD CONSTRAINT `RESPUESTAS_preguntaId_fkey` FOREIGN KEY (`preguntaId`) REFERENCES `PREGUNTAS`(`idPREGUNTAS`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_aspiranteId_fkey` FOREIGN KEY (`aspiranteId`) REFERENCES `ASPIRANTE`(`idASPIRANTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_preguntaId_fkey` FOREIGN KEY (`preguntaId`) REFERENCES `PREGUNTAS`(`idPREGUNTAS`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_respuestaId_fkey` FOREIGN KEY (`respuestaId`) REFERENCES `RESPUESTAS`(`idRESPUESTAS`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS_ASPIRANTE` ADD CONSTRAINT `RESPUESTAS_ASPIRANTE_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE RESTRICT ON UPDATE CASCADE;
