-- CreateTable
CREATE TABLE `ADMIN` (
    `idADMIN` INTEGER NOT NULL,
    `nombre` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `ADMIN_email_key`(`email`),
    PRIMARY KEY (`idADMIN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TEST` (
    `idTEST` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idTEST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ASPIRANTE` (
    `idASPIRANTE` INTEGER NOT NULL,
    `nombre_completo` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `telefono` VARCHAR(10) NOT NULL,
    `password` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`idASPIRANTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REPORTE` (
    `idREPORTE` INTEGER NOT NULL AUTO_INCREMENT,
    `Fecha` DATETIME(3) NOT NULL,
    `TEST_idTEST` INTEGER NOT NULL,
    `aspiranteId` INTEGER NOT NULL,
    `adminId` INTEGER NOT NULL,

    UNIQUE INDEX `REPORTE_TEST_idTEST_key`(`TEST_idTEST`),
    PRIMARY KEY (`idREPORTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AREA` (
    `idAREA` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,
    `reporteId` INTEGER NOT NULL,

    PRIMARY KEY (`idAREA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PROGRAMA` (
    `idPROGRAMA` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(50) NOT NULL,
    `descripcion` VARCHAR(500) NOT NULL,
    `categoriaId` INTEGER NOT NULL,
    `ambienteId` INTEGER NOT NULL,
    `areaId` INTEGER NOT NULL,

    UNIQUE INDEX `PROGRAMA_ambienteId_key`(`ambienteId`),
    PRIMARY KEY (`idPROGRAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIA` (
    `idCATEGORIA` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `nombre` VARCHAR(50) NOT NULL,
    `redesid` INTEGER NOT NULL,

    PRIMARY KEY (`idCATEGORIA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REDES` (
    `idREDES` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idREDES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AMBIENTE` (
    `idAMBIENTE` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `caracteristicas` VARCHAR(500) NOT NULL,
    `centroId` INTEGER NOT NULL,

    PRIMARY KEY (`idAMBIENTE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CENTRO` (
    `idCENTRO` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,

    PRIMARY KEY (`idCENTRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PREGUNTAS` (
    `idPREGUNTAS` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `testId` INTEGER NOT NULL,

    PRIMARY KEY (`idPREGUNTAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESPUESTAS` (
    `idRESPUESTAS` INTEGER NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(500) NOT NULL,
    `preguntaId` INTEGER NOT NULL,

    PRIMARY KEY (`idRESPUESTAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_TEST_idTEST_fkey` FOREIGN KEY (`TEST_idTEST`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_aspiranteId_fkey` FOREIGN KEY (`aspiranteId`) REFERENCES `ASPIRANTE`(`idASPIRANTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTE` ADD CONSTRAINT `REPORTE_adminId_fkey` FOREIGN KEY (`adminId`) REFERENCES `ADMIN`(`idADMIN`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AREA` ADD CONSTRAINT `AREA_reporteId_fkey` FOREIGN KEY (`reporteId`) REFERENCES `REPORTE`(`idREPORTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_categoriaId_fkey` FOREIGN KEY (`categoriaId`) REFERENCES `CATEGORIA`(`idCATEGORIA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_ambienteId_fkey` FOREIGN KEY (`ambienteId`) REFERENCES `AMBIENTE`(`idAMBIENTE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRAMA` ADD CONSTRAINT `PROGRAMA_areaId_fkey` FOREIGN KEY (`areaId`) REFERENCES `AREA`(`idAREA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CATEGORIA` ADD CONSTRAINT `CATEGORIA_redesid_fkey` FOREIGN KEY (`redesid`) REFERENCES `REDES`(`idREDES`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AMBIENTE` ADD CONSTRAINT `AMBIENTE_centroId_fkey` FOREIGN KEY (`centroId`) REFERENCES `CENTRO`(`idCENTRO`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PREGUNTAS` ADD CONSTRAINT `PREGUNTAS_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `TEST`(`idTEST`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESPUESTAS` ADD CONSTRAINT `RESPUESTAS_preguntaId_fkey` FOREIGN KEY (`preguntaId`) REFERENCES `PREGUNTAS`(`idPREGUNTAS`) ON DELETE RESTRICT ON UPDATE CASCADE;
